[book]
title = "飞腾派驱动开发实验指导书"
author = "opencamp 社区"
language = "zh-CN"
src = "src"

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
